### ISSUE TITLE
hip_impl::make_kernarg throws an exception

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCm-Developer-Tools/HIP#1288]
I am trying to get tensorflow 1.14 to run with a hand-built ROCm (including HIP.) I'm using the latest git.

I got to the point where it all loads and then I get an C++ exception. 

The relevant gdb trace is:
```

#5  0x00007f23fb04b5bd in __cxxabiv1::__cxa_throw (obj=<optimized out>,
    tinfo=0x7f23fb182330 <typeinfo for std::exception>, dest=0x7f23fb04a440 <std::exception::~exception()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007f23fa99467f in hip_impl::hip_throw(std::exception const&) () from /opt/rocm/lib/libhip_hcc.so
#7  0x00007f23fa96fe24 in hip_impl::program_state_impl::kernargs_size_align(unsigned long) ()
   from /opt/rocm/lib/libhip_hcc.so
#8  0x00007f23fa96fb89 in hip_impl::program_state::get_kernargs_size_align(unsigned long) ()
   from /opt/rocm/lib/libhip_hcc.so
#9  0x00007f2400ef7371 in std::vector<unsigned char, std::allocator<unsigned char> > hip_impl::make_kernarg<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::Tens                                             orConversionOp<float, Eigen::TensorMap<Eigen::Tensor<long long const, 1, 1, long>, 16, Eigen::MakePointer> const> const>                                              const, Eigen::GpuDevice>, long, Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1                                             , long>, 16, Eigen::MakePointer>, Eigen::TensorConversionOp<float, Eigen::TensorMap<Eigen::Tensor<long long const, 1, 1,                                              long>, 16, Eigen::MakePointer> const> const> const, Eigen::GpuDevice>, long>(void (*)(Eigen::TensorEvaluator<Eigen::Ten                                             sorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorConversionOp<float, Eigen::TensorMap<Eigen::Tensor<long long const, 1, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::GpuDev                                             ice>, long), std::tuple<Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>,                                              16, Eigen::MakePointer>, Eigen::TensorConversionOp<float, Eigen::TensorMap<Eigen::Tensor<long long const, 1, 1, long>, 1                                             6, Eigen::MakePointer> const> const> const, Eigen::GpuDevice>, long>) ()
   from /usr/lib/python2.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#10 0x00007f2400ef726e in Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorConversionOp<float, Eigen::TensorMap<Eigen::Tensor<long long const, 1,                                              1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::GpuDevice, false, false>::run(Eigen::TensorAssignOp<Eigen:                                             :TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorConversionOp<float, Eigen::TensorMap<                                             Eigen::Tensor<long long const, 1, 1, long>, 16, Eigen::MakePointer> const> const> const&, Eigen::GpuDevice const&) ()
   from /usr/lib/python2.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#11 0x00007f2400eb224d in tensorflow::functor::CastFunctor<Eigen::GpuDevice, float, long long>::operator()(Eigen::GpuDevice const&, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorMap<Eigen::Tensor<l                                             ong long const, 1, 1, long>, 16, Eigen::MakePointer>, bool) ()
   from /usr/lib/python2.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#12 0x00007f2400e95ec8 in std::_Function_handler<void (tensorflow::OpKernelContext*, tensorflow::Tensor const&, tensorflow::Tensor*, bool), tensorflow::GetGpuCastFromInt64(tensorflow::DataType)::{lambda(tensorflow::OpKernelContext*, tensorf                                             low::Tensor const&, tensorflow::Tensor*, bool)#10}>::_M_invoke(std::_Any_data const&, tensorflow::OpKernelContext*&&, te                                             nsorflow::Tensor const&, tensorflow::Tensor*&&, bool&&) ()
   from /usr/lib/python2.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so
#13 0x00007f2400e61c6e in tensorflow::CastOpBase::Compute(tensorflow::OpKernelContext*) ()

```

Upon some investigation, it looks like tensorflow is trying to launch the aforementioned kernel and that process involves finding the size of its arguments (function kernargs_size_align() in src/program_state.inl.)
In that function, the first test (checking that the kernel exists) is successful (the entry is found in the container returned by get_function_names()), but the second test fails (the entry is not in the container returned by get_kernargs().)
That is because the first container has ~300,000 entries, but the second only has  a handful (what looks like the kernels actually implemented on the GPU, the ones from rocrand.so, rocblas.so, etc.)

I don't understand how this is supposed to work. Did I somehow build this wrong, or is it a bug?

**Comment by ekuznetsov139** [comment]
I've sorted it out (I think). The tensorflow library itself needs to be built with hcc. I did
```
bazel clean
export CC=/opt/rocm/bin/hcc
export CXX=/opt/rocm/bin/hcc
```
reconfigured, rebuilt, and now it runs. It even uses the GPU (the chip gets to 56 C).

It does not run very well (with an AMD Radeon RX Vega 64, I'm seeing about 1/10th the speed I'm getting on an NVIDIA GeForce 1080i using the exact same tensorflow model), but it's a big step in the right direction.

**Comment by ekuznetsov139** [comment]
And the biggest reason it wasn't running very well is that several tensorflow ops (all reduction ops and Relu) were not ROCm-enabled. Consequently, a lot of processing was CPU-side and a lot of data had to be shuffled back and forth over the PCIe bus.

Reenabling the missed ops was trivial: https://github.com/ekuznetsov139/tensorflow/commit/6f016006575afaad88b7352a8284b2a8b338857f
(I had to skip complex64 and complex128 versions, they weren't compiling, but all others worked fine.)

That gets me up to 50% of the speed of the 1080i.
