### ISSUE TITLE
hipGetDeviceProperties produces Segmentation fault on AMD machines. 

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1407]
hipGetDeviceProperties produce Segmentation fault on AMD machines when optimization flags like O1 or -O2  are employed:

```
cat test.cpp
#include "hip/hip_runtime.h"
int main () 
{
  int idevice = 0;
  hipSetDevice(idevice);
  hipDeviceProp_t dprops;
  hipGetDeviceProperties( &dprops, idevice );
return 0;
}   
```
```
 $ hipcc -O2    -o test test.cpp && ./test
Segmentation fault
```
and it works fine without -O2
`hipcc -O2    -o test test.cpp && ./test`
additional details:

```
$ hipconfig 
HIP version  : 2.8.19356-29d09eb2

== hipconfig
HIP_PATH     : /home/k/software/hip
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/home/k/software/hip/include -I/opt/rocm/hcc/include -I/opt/rocm/hsa/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 9.0.0 (/data/jenkins_workspace/compute-rocm-rel-2.7/external/hcc-tot/clang 5c2570257a8bbd74eff632fbc60692ef61ef8ecb) (/data/jenkins_workspace/compute-rocm-rel-2.7/external/hcc-tot/compiler 9a9477021e6998100ff64d1360dcfe64f65cebe5) (based on HCC 2.7.19315-346267d-5c25702-9a94770 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
LLVM (http://llvm.org/):
  LLVM version 9.0.0svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/home/k/software/hip/bin:/usr/lib/llvm-9//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/opt/rocm//bin
HIP_ROOT=/home/k/software/hip
LD_LIBRARY_PATH=/home/k/software/hip/lib:/usr/lib/llvm-9//lib::/opt/rocm//lib:/home//software/lib/rocRAND/hiprand/lib:/home/k/software/lib/rocRAND/rocrand/lib

== Linux Kernel
Hostname     : zam101
Linux zam101 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by Kaveh01** [comment]
@SarbojitAMD 
Sorry, I forgot to attach the binary
[1407.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3609795/1407.tar.gz)

**Comment by SarbojitAMD** [comment]
@Kaveh01, Can you build the app with debug flag enabled (-g) and share core and binary files again?

**Comment by Kaveh01** [comment]
@SarbojitAMD 
Sure.
[1407.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3625164/1407.tar.gz)

**Comment by SarbojitAMD** [comment]
Thank for your prompt response. however, I could not conclude much as the core file did not show-up where exactly in hip runtime time we have hit the crash. Can you run the application with "HIP_DB=0xF <application>" and share the output you see?

Note: HIP_DB enables extra logs which can be helpful in order to locate the culprit function.

**Comment by Kaveh01** [comment]
Thanks for your replay. This is the output:

```
HIP_DB=0xf [api+sync+mem+copy]
  hip-api pid:119663 tid:1:HIP initialized short_tid#1 (maps to full_tid: 0x7fe6e0227fc0)
  hip-sync pid:119663 tid:1:locking criticalData=0x1734498 for ctx:0x1734480.dev:0..
  hip-sync pid:119663 tid:1: addStream: stream:0.0
  hip-copy pid:119663 tid:1:resetPeerWatchers for context=ctx:0x1734480.dev:0
  hip-copy pid:119663 tid:1:addPeerWatcher.  Allocations on ctx:0x1734480.dev:0 now visible to peerWatcher ctx:0x1734480.dev:0.
  hip-sync pid:119663 tid:1:created ctx with defaultStream=0x1738270 (stream:0.0)
  hip-sync pid:119663 tid:1:auto-unlocking criticalData=0x1734498 for ctx:0x1734480.dev:0...
  hip-sync pid:119663 tid:1:pid=119663 <ihipInit>                     g_numLogicalThreads=16
<<hip-api pid:119663 tid:1.1 hipSetDevice (0) @1905673047064043
  hip-api pid:119663 tid:1.1 hipSetDevice                   ret= 0 (hipSuccess)>> +4310 ns
<<hip-api pid:119663 tid:1.2 hipGetDeviceProperties (0x7ffe69c032d8, 0) @1905673047084173
  hip-api pid:119663 tid:1.2 hipGetDeviceProperties         ret= 0 (hipSuccess)>> +4120 ns
Segmentation fault
```

**Comment by SarbojitAMD** [comment]
From HIP trace it does not look like segmentation fault is happening inside HIP library. You can share gdb backtrace, variables at the time of seg-fault and in passing case.

**Comment by Kaveh01** [comment]
@SarbojitAMD 
I guess I should look for the error somewhere else. It as you mentioned it is not in HIP:
```
Reading symbols from a.out...done.
(gdb) run
Starting program: /home/kaveh/HIP-bug/1407/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff134f700 (LWP 122298)]

Thread 1 "a.out" received signal SIGSEGV, Segmentation fault.
0x000000007fffffff in ?? ()
(gdb) bt
#0  0x000000007fffffff in ?? ()
#1  0x0000000000000000 in ?? ()
```
Thanks.
