### ISSUE TITLE
How to install legacy HIP stable version via apt-get?

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#1432]
ROCm Ubuntu repo is always upgrading so that many existing applications based on legacy RICn version cannot execute correctly. However, seems like old ROCm packages in apt-get have been override by new version, thus legacy HIP environment like ROCm 2.6 is not able to reproduce.

**Comment by ghostplant** [comment]
```sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /opt/rocm/lib/librccl.so: undefined symbol: hipExtLaunchMultiKernelMultiDevice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tf_example.py", line 3, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /opt/rocm/lib/librccl.so: undefined symbol: hipExtLaunchMultiKernelMultiDevice


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

This is mainly caused by rccl package for rocm-2.6 is no longer available in ubuntu repo.

**Comment by mangupta** [comment]
Did you try http://repo.radeon.com/rocm/apt/2.6/?

**Comment by ghostplant** [comment]
@mangupta Yes, it works! I think many legacy rocm images from docker hub should also use the fixed version repo, otherwise they cannot be served properly.
