### ISSUE TITLE
Hipification issue

### ISSUE THREAD

**Issue by chinchoretej** [ROCm-Developer-Tools/HIP#1655]
After using hipconvertinplace-perl.sh command I'm getting following warning:
![warning](https://user-images.githubusercontent.com/47495669/68859146-ad7eed00-070c-11ea-8213-d8a79d36f59f.png)

According to my observation this is because of this following two functions:

template<class Scalar>
__global__
void cudaEncode(const uint maxbits,
           const Scalar* scalars,
           Word *stream,
           const uint3 dims,
           const int3 stride,
           const uint3 padded_dims,
           const uint tot_blocks) { Some commands written over here}
.
.
.
hipLaunchKernelGGL(cudaEncode<Scalar>, dim3(grid_size), dim3(block_size), 0, 0, maxbits,
     d_data,
     stream,
     dims,
     stride,
     zfp_pad,
     zfp_blocks);

Will you please tell me exactly what is the problem. Because of this warning, while testing the application I'm getting following error:
Error: Missing metadata for __global__ function

**Comment by chinchoretej** [comment]
If I'm replacing cudaEncode with hipEncode the warnings got resolved. But while testing the ported application, still I'm getting the error: missing metadata for global function

**Comment by emankov** [comment]
It's a known issue with multiple in-place hipification; there is a feature request for it: #1246. I'm working on it currently. Could you please hipify not in-place till the feature is implemented?

**Comment by anilbommareddy** [comment]
while using with hipify-perl also there is an issue with hipLaunchKernelGGL(as above comment), and replacing cudaEncode with hipEncode the warnings got resolved
cuda_]$ /opt/rocm/hip/bin/hipify-perl  decode1.cuh > decode1.cpp
  warning: decode1.cuh:#32 : cudaDecode1(Word *blocks,
  warning: decode1.cuh:#116 :   hipLaunchKernelGGL(cudaDecode1<scalar>,dim3(grid_size),dim3(block_size),0,0,stream, d_data, dim, stride, zfp_pad, zfp_blocks,maxbits);
decode1.cpp

**Comment by emankov** [comment]
Currently, there is no solution for implementing include files dependency graph in `hipify-perl`. You have two options here:
1. Do not use `--inplace` option.
2. To form the list of input source files manually.

**Comment by bensander** [comment]
Can we fix this for hipify Perl?

On Nov 21, 2019, at 7:15 AM, Evgeny Mankov <notifications@github.com> wrote:

﻿ [CAUTION: External Email]

Currently, there is no solution for implementing include files dependency graph in hipify-perl. You have two options here:

  1.  Do not use --inplace option.
  2.  To form the list of input source files manually.

**Comment by emankov** [comment]
@bensander, implementing it for hipify-clang (#1246) is in progress. The upcoming solution is based on include header files dependency graph. As for hipify-perl, I will think about it more, but currently I have no solution to implement the same in it.

**Comment by anilbommareddy** [comment]
I think, Issue still exists with the  list of input source files manually.
Example:
[taccuser@ROCm-CentOS76-2 bin]$ ./testZfpCuda1dDouble
[==========] Running 5 test(s).
[ RUN      ] when_seededRandomSmoothDataGenerated_expect_ChecksumMatches
[       OK ] when_seededRandomSmoothDataGenerated_expect_ChecksumMatches
[ RUN      ] given_Cuda_1dDoubleReversedArray_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch
terminate called after throwing an instance of 'std::runtime_error'
what():  Missing metadata for __global__ function: _ZN5cuZFP10hipEncode1IdEEvjPKT_Pyjijj

[BackTrace]

#0  0x00007ffff677c207 in raise () from /lib64/libc.so.6
#1  0x00007ffff677d8f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff58537d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007ffff5851746 in ?? () from /lib64/libstdc++.so.6
#4  0x00007ffff5851773 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007ffff5851993 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007ffff5b3ce4e in hip_impl::hip_throw(std::exception const&) () from /opt/rocm/hip/lib/libhip_hcc.so
#7  0x00007ffff5b15ce7 in hip_impl::program_state_impl::kernargs_size_align(unsigned long) () from /opt/rocm/hip/lib/libhip_hcc.so
#8  0x00007ffff5b158b9 in hip_impl::program_state::get_kernargs_size_align(unsigned long) () from /opt/rocm/hip/lib/libhip_hcc.so
#9  0x00007ffff7a830ce in hip_impl::kernarg hip_impl::make_kernarg<unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int, unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int>(void (*)(unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int), std::tuple<unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int>) () from /home/taccuser/Desktop/Anil_Bommareddy/zfp_old/build/lib64/libzfp.so.0
#10 0x00007ffff7a82f4f in void hipLaunchKernelGGL<unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int, void (*)(unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int)>(void (*)(unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int), dim3 const&, dim3 const&, unsigned int, ihipStream_t*, unsigned int, double const*, unsigned long long*, unsigned int, int, unsigned int, unsigned int) ()
   from /home/taccuser/Desktop/Anil_Bommareddy/zfp_old/build/lib64/libzfp.so.0
#11 0x00007ffff7a82ddd in unsigned long cuZFP::encode1launch<double>(unsigned int, int, double const*, unsigned long long*, int) ()
   from /home/taccuser/Desktop/Anil_Bommareddy/zfp_old/build/lib64/libzfp.so.0
#12 0x00007ffff7a82b11 in unsigned long cuZFP::encode1<double>(int, int, double*, unsigned long long*, int) ()
   from /home/taccuser/Desktop/Anil_Bommareddy/zfp_old/build/lib64/libzfp.so.0
#13 0x00007ffff7a7aad7 in unsigned long internal::encode<double>(unsigned int*, HIP_vector_type<int, 3u>, int, double*, unsigned long long*) ()
   from /home/taccuser/Desktop/Anil_Bommareddy/zfp_old/build/lib64/libzfp.so.0
#14 0x00007ffff7a7a45d in cuda_compress () from /home/taccuser/Desktop/Anil_Bommareddy/zfp_old/build/lib64/libzfp.so.0
#15 0x00007ffff7a5f9f7 in zfp_compress () from /home/taccuser/Desktop/Anil_Bommareddy/zfp_old/build/lib64/libzfp.so.0
#16 0x000000000040328f in runCompressDecompressTests.constprop.8 ()
#17 0x0000000000408d26 in cmocka_run_one_test_or_fixture ()
#18 0x0000000000408fd3 in cmocka_run_one_tests ()
#19 0x00000000004093e5 in _cmocka_run_group_tests ()

**Comment by emankov** [comment]
> I think, **Issue still exists with the list of input source files manually.**
> Example:
> [taccuser@ROCm-CentOS76-2 bin]$ ./testZfpCuda1dDouble
> [==========] Running 5 test(s).
> [ RUN ] when_seededRandomSmoothDataGenerated_expect_ChecksumMatches
> [ OK ] when_seededRandomSmoothDataGenerated_expect_ChecksumMatches
> [ RUN ] given_Cuda_1dDoubleReversedArray_when_ZfpCompressDecompressFixedRate_expect_BitstreamAndArrayChecksumsMatch
> terminate called after throwing an instance of 'std::runtime_error'
> what(): **Missing metadata for global function: _ZN5cuZFP10hipEncode1IdEEvjPKT_Pyjijj**

Nope, it is a runtime issue, definitely unrelated to in-place hipification of multiple files.

**Comment by emankov** [comment]
@chinchoretej, could you please confirm, that the sorting of input files is correct for hipify-clang? As for hipify-perl, I'm still thinking of how to implement the same in it.

**Comment by chinchoretej** [comment]
@emankov 
I have compiled the files with -fno-gpu-rdc flag and the problem is solved. I have not tried with hipify-clang.
So, I think there is no file dependency issues.
eg. hipcc -fno-gpu-rdc
