### ISSUE TITLE
Global variables inside anonymous namespaces issue

### ISSUE THREAD

**Issue by tpadioleau** [ROCm-Developer-Tools/HIP#3246]
I am having an issue with global variables inside anonymous namespaces.

```cpp
#include <hip/hip_runtime.h>

#define HIP_THROW_ON_ERROR(val) hip_throw_on_error((val), #val, __FILE__, __LINE__)
template <class T>
void hip_throw_on_error(T const err, const char* const func, const char* const file, const int line)
{
    if (err != hipSuccess) {
        std::stringstream ss;
        ss << "HIP Runtime Error at: " << file << ":" << line << "\n";
        ss << hipGetErrorString(err) << " " << func << "\n";
        throw std::runtime_error(ss.str());
    }
}

namespace {

__device__ int g_var;

__global__ void print_var()
{
  printf("g_var=%d\n", g_var);
}
  
}

int main()
{
  int var = 2;
  HIP_THROW_ON_ERROR(hipMemcpyToSymbol(HIP_SYMBOL(g_var), &var, sizeof(int)));
  print_var<<<1, 1>>>();
  HIP_THROW_ON_ERROR(hipDeviceSynchronize());
}
```
The code above generates an error: `"Cannot create GlobalVar Obj"` with the following call stack
```
#0  0x0000155552aa9a9f in raise () from /lib64/libc.so.6
#1  0x0000155552a7ce05 in abort () from /lib64/libc.so.6
#2  0x0000155553460e81 in amd::report_fatal(char const*, int, char const*) ()
   from /opt/rocm-5.3.0/lib/libamdhip64.so.5
#3  0x0000155553289f72 in hip::DeviceVar::DeviceVar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ihipModule_t*) ()
   from /opt/rocm-5.3.0/lib/libamdhip64.so.5
#4  0x000015555328a78f in hip::Var::getStatDeviceVar(hip::DeviceVar**, int) ()
   from /opt/rocm-5.3.0/lib/libamdhip64.so.5
#5  0x0000155553246d52 in hip::StatCO::getStatGlobalVar(void const*, int, void**, unsigned long*) () from /opt/rocm-5.3.0/lib/libamdhip64.so.5
#6  0x000015555334790d in ihipMemcpySymbol_validate(void const*, unsigned long, unsigned long, unsigned long&, void*&) ()
   from /opt/rocm-5.3.0/lib/libamdhip64.so.5
#7  0x00001555532fa283 in hipMemcpyToSymbol_common(void const*, void const*, unsigned long, unsigned long, hipMemcpyKind, ihipStream_t*) ()
   from /opt/rocm-5.3.0/lib/libamdhip64.so.5
#8  0x0000155553303728 in hipMemcpyToSymbol ()
   from /opt/rocm-5.3.0/lib/libamdhip64.so.5
#9  0x000000000020cba8 in main ()
```

If I remove the anonymous namespace or use a named namespace it works fine. To compile the code I use the command: `hipcc -g --offload-arch=gfx90a main.cpp`. 

Any an idea about what is going wrong ?

**Comment by jatinx** [comment]
It seems compiler is removing the __device__ variable from code object if the variable is in unnamed namespace.

Will look into it.

**Comment by yxsamliu** [comment]
This seems to be a clang bug. I have a fix for it: https://reviews.llvm.org/D152164

**Comment by tpadioleau** [comment]
Thanks a lot for the bug fix, can you tell the version of hipcc/clang it shall be available ?

**Comment by BenWibking** [comment]
The commit with the fix was not incorporated in the git log for rocm-5.7.0. Hopefully it will appear in the next release. Can anyone from AMD comment on this?
